version: '3'
services:
  lb4_app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_USER: lb4
      MYSQL_PASSWORD: lb4
      MYSQL_DATABASE: lb4db
      MYSQL_ROOT_PASSWORD: lb4root
    volumes:
      - mysqldata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
volumes:
  mysqldata:
